### ISSUE TITLE
Mini Map

### ISSUE THREAD

**Issue by CaptainLucster** [YOYOK9/BusinessElite-Plus#20] opened 2017-12-30 22:33 UTC
#### Issue Description:

The minimap overlay (shows you, time, coordinates, biome, way points, and direction) deosn't appear. 

#### What Happens:

the overlay doesn't show up unless you open the full screen map, then it shows up for only a second then disappears again.

#### What you Expected to happen:

For there to be the overlay

#### Steps to Reproduce:

open the game, and look at the top right corner with yer eye balls.

#### Does it happen on the Server:

yes

#### Pack/Mods Versions: Ex(V1.5.3)

Mod   -> 5.6.0b1
server -> 1.9.2 (beta) (current)

#### Your most recent log file where the issue was present:  ex(log folder or crash reports)
(do not leave blank)

I have no clue what this is or where to find it, an explanation of what to google (i tried but only found stuff about chat logs) or a file location would be helpful!

**Comment by YOYOK9** [comment] 2017-12-31 00:03
Duplicate of #18

**Closed** 2017-12-31 00:03 UTC
Labels: duplicate, Other Mod
